# Configure kubectl as described here: https://stackoverflow.com/questions/51535654/kubectl-apply-command-does-not-work-gives-connection-refused-error
- name: create directory that contains kube admin config for root user
  file: path=/root/.kube state=directory mode=0755
- name: copy kubernetes admin config to root home
  command: cp -i /etc/kubernetes/admin.conf /root/.kube/config