- name: add gpg key for kubernetes packages
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: add kubernetes repository as an apt repository
  apt_repository:
    repo: deb  http://apt.kubernetes.io/  kubernetes-xenial  main
    state: present
- name: install kubelet, kubeadm and kubectl
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - kubeadm=1.14.1-00
    - kubelet=1.14.1-00
    - kubectl=1.14.1-00
- name: mark packages as hold
  command: apt-mark hold kubelet kubeadm kubectl
  